{
  "openapi": "3.0.0",
  "info": {
    "title": "Etomin API",
    "description": "This is the Etomin payment API.\nYou can view the transactions generated by these services at [http://panel.etomin.com](http://panel.etomin.com).\nIt is necessary to obtain an account on Etomin to use this API.\n# Introduction\nIn this space you can find the services to accept online payments with Etomin.\n# Authentication\nAll services require an \"Authorization\" token to process through Etomin, you need to create an account first.\n## Bearer Authentication\nBearer authentication (also called token authentication) is an HTTP authentication scheme that involves security tokens called bearer tokens. The name “Bearer authentication” can be understood as “give access to the bearer of this token.” The bearer token is a cryptic string, usually generated by the server in response to a login request. The client must send this token in the Authorization header when making requests to protected resources:\n` Authorization: Bearer <token> `\n",
    "version": "2.0.1",
    "contact": {
      "name": "API Support",
      "email": "desarrollo@etomin.com",
      "url": "https://panel.etomin.com/"
    },
    "x-logo": {
      "url": "https://panel.etomin.com/assets/images/etomin.png",
      "altText": "Etomin logo"
    }
  },
  "tags": [
    {
      "name": "SignUp",
      "description": "Create account"
    },
    {
      "name": "SignIn",
      "description": "Get authorization account"
    },
    {
      "name": "Sale",
      "description": "Generate a Sale"
    },
    {
      "name": "Get Cards",
      "description": "Get tokenized cards"
    }
  ],
  "x-tagGroups": [
    {
      "name": "General",
      "tags": [
        "SignUp",
        "SignIn",
        "Sale",
        "Get Cards"
      ]
    },
    {
      "name": "Sale Management",
      "tags": [
        "Sale",
        "Refund",
        "Reversal"
      ]
    }
  ],
  "servers": [
    {
      "url": "https://pagos.etomin.com/api/v1/",
      "description": "Base URL"
    }
  ],
  "paths": {
    "/signup": {
      "post": {
        "summary": "Create an account",
        "tags": [
          "SignUp"
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "companyName": {
                    "type": "string",
                    "description": "Name of the company"
                  },
                  "fullName": {
                    "type": "string",
                    "description": "Full name of the user"
                  },
                  "email": {
                    "type": "string",
                    "description": "Email address of the user"
                  },
                  "password": {
                    "type": "string",
                    "description": "Password for the account"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Account created successfully",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "companyName": {
                      "type": "string"
                    },
                    "fullName": {
                      "type": "string"
                    },
                    "email": {
                      "type": "string"
                    },
                    "mode": {
                      "type": "string"
                    },
                    "type": {
                      "type": "string"
                    },
                    "error": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          },
          "403": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/signin": {
      "post": {
        "summary": "Get authorization account",
        "tags": [
          "SignIn"
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "email": {
                    "type": "string",
                    "description": "Email address of the user"
                  },
                  "password": {
                    "type": "string",
                    "description": "Password for the account"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Authorization successful",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "authToken": {
                      "type": "string",
                      "description": "Authorization token for accessing protected resources"
                    },
                    "expiresIn": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          },
          "403": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/sale": {
      "post": {
        "tags": [
          "Sale"
        ],
        "summary": "Generate a Sale",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "oneOf": [
                  {
                    "properties": {
                      "amount": {
                        "type": "number",
                        "description": "Sale amount"
                      },
                      "currency": {
                        "type": "string",
                        "description": "Currency code"
                      },
                      "reference": {
                        "type": "string",
                        "description": "Transaction reference"
                      },
                      "customerInformation": {
                        "type": "object",
                        "properties": {
                          "firstName": {
                            "type": "string",
                            "description": "Customer's first name"
                          },
                          "lastName": {
                            "type": "string",
                            "description": "Customer's last name"
                          },
                          "middleName": {
                            "type": "string",
                            "description": "Customer's middle name"
                          },
                          "email": {
                            "type": "string",
                            "description": "Customer's email address"
                          },
                          "phone1": {
                            "type": "string",
                            "description": "Customer's phone number"
                          },
                          "city": {
                            "type": "string",
                            "description": "Customer's city"
                          },
                          "address1": {
                            "type": "string",
                            "description": "Customer's address"
                          },
                          "postalCode": {
                            "type": "string",
                            "description": "Customer's postal code"
                          },
                          "state": {
                            "type": "string",
                            "description": "Customer's state"
                          },
                          "country": {
                            "type": "string",
                            "description": "Customer's country"
                          },
                          "ip": {
                            "type": "string",
                            "description": "Customer's IP address"
                          }
                        }
                      },
                      "cardData": {
                        "type": "object",
                        "properties": {
                          "cardNumber": {
                            "type": "string",
                            "description": "Credit card number"
                          },
                          "cvv": {
                            "type": "string",
                            "description": "Credit card security code (CVV)"
                          },
                          "cardholderName": {
                            "type": "string",
                            "description": "Name of the cardholder"
                          },
                          "expirationYear": {
                            "type": "string",
                            "description": "Card expiration year"
                          },
                          "expirationMonth": {
                            "type": "string",
                            "description": "Card expiration month"
                          }
                        }
                      }
                    }
                  },
                  {
                    "properties": {
                      "amount": {
                        "type": "number",
                        "description": "Sale amount"
                      },
                      "currency": {
                        "type": "string",
                        "description": "Currency code"
                      },
                      "reference": {
                        "type": "string",
                        "description": "Transaction reference"
                      },
                      "customerInformation": {
                        "type": "object",
                        "properties": {
                          "firstName": {
                            "type": "string",
                            "description": "Customer's first name"
                          },
                          "lastName": {
                            "type": "string",
                            "description": "Customer's last name"
                          },
                          "middleName": {
                            "type": "string",
                            "description": "Customer's middle name"
                          },
                          "email": {
                            "type": "string",
                            "description": "Customer's email address"
                          },
                          "phone1": {
                            "type": "string",
                            "description": "Customer's phone number"
                          },
                          "city": {
                            "type": "string",
                            "description": "Customer's city"
                          },
                          "address1": {
                            "type": "string",
                            "description": "Customer's address"
                          },
                          "postalCode": {
                            "type": "string",
                            "description": "Customer's postal code"
                          },
                          "state": {
                            "type": "string",
                            "description": "Customer's state"
                          },
                          "country": {
                            "type": "string",
                            "description": "Customer's country"
                          },
                          "ip": {
                            "type": "string",
                            "description": "Customer's IP address"
                          }
                        }
                      },
                      "cardData": {
                        "type": "object",
                        "properties": {
                          "cardNumber": {
                            "type": "string",
                            "description": "Credit card number"
                          },
                          "cvv": {
                            "type": "string",
                            "description": "Credit card security code (CVV)"
                          },
                          "cardholderName": {
                            "type": "string",
                            "description": "Name of the cardholder"
                          },
                          "expirationYear": {
                            "type": "string",
                            "description": "Card expiration year"
                          },
                          "expirationMonth": {
                            "type": "string",
                            "description": "Card expiration month"
                          }
                        }
                      },
                      "redirectUrl": {
                        "type": "string",
                        "description": "Redirect URL with response"
                      }
                    }
                  },
                  {
                    "properties": {
                      "amount": {
                        "type": "number",
                        "description": "Sale amount"
                      },
                      "currency": {
                        "type": "string",
                        "description": "Currency code"
                      },
                      "reference": {
                        "type": "string",
                        "description": "Transaction reference"
                      },
                      "customerInformation": {
                        "type": "object",
                        "properties": {
                          "firstName": {
                            "type": "string",
                            "description": "Customer's first name"
                          },
                          "lastName": {
                            "type": "string",
                            "description": "Customer's last name"
                          },
                          "middleName": {
                            "type": "string",
                            "description": "Customer's middle name"
                          },
                          "email": {
                            "type": "string",
                            "description": "Customer's email address"
                          },
                          "phone1": {
                            "type": "string",
                            "description": "Customer's phone number"
                          },
                          "city": {
                            "type": "string",
                            "description": "Customer's city"
                          },
                          "address1": {
                            "type": "string",
                            "description": "Customer's address"
                          },
                          "postalCode": {
                            "type": "string",
                            "description": "Customer's postal code"
                          },
                          "state": {
                            "type": "string",
                            "description": "Customer's state"
                          },
                          "country": {
                            "type": "string",
                            "description": "Customer's country"
                          },
                          "ip": {
                            "type": "string",
                            "description": "Customer's IP address"
                          }
                        }
                      },
                      "cardData": {
                        "type": "object",
                        "properties": {
                          "cardNumberToken": {
                            "type": "string",
                            "description": "Card token"
                          },
                          "cvv": {
                            "type": "string",
                            "description": "Credit card security code (CVV)"
                          }
                        }
                      }
                    }
                  },
                  {
                    "properties": {
                      "amount": {
                        "type": "number",
                        "description": "Sale amount"
                      },
                      "currency": {
                        "type": "string",
                        "description": "Currency code"
                      },
                      "reference": {
                        "type": "string",
                        "description": "Transaction reference"
                      },
                      "customerInformation": {
                        "type": "object",
                        "properties": {
                          "firstName": {
                            "type": "string",
                            "description": "Customer's first name"
                          },
                          "lastName": {
                            "type": "string",
                            "description": "Customer's last name"
                          },
                          "middleName": {
                            "type": "string",
                            "description": "Customer's middle name"
                          },
                          "email": {
                            "type": "string",
                            "description": "Customer's email address"
                          },
                          "phone1": {
                            "type": "string",
                            "description": "Customer's phone number"
                          },
                          "city": {
                            "type": "string",
                            "description": "Customer's city"
                          },
                          "address1": {
                            "type": "string",
                            "description": "Customer's address"
                          },
                          "postalCode": {
                            "type": "string",
                            "description": "Customer's postal code"
                          },
                          "state": {
                            "type": "string",
                            "description": "Customer's state"
                          },
                          "country": {
                            "type": "string",
                            "description": "Customer's country"
                          },
                          "ip": {
                            "type": "string",
                            "description": "Customer's IP address"
                          }
                        }
                      },
                      "cardData": {
                        "type": "object",
                        "properties": {
                          "cardNumberToken": {
                            "type": "string",
                            "description": "Card token"
                          },
                          "cvv": {
                            "type": "string",
                            "description": "Credit card security code (CVV)"
                          }
                        }
                      },
                      "planName": {
                        "type": "string",
                        "description": "Recurrence plan name"
                      },
                      "recurrence": {
                        "type": "string",
                        "description": "Recurrence value"
                      },
                      "startDate": {
                        "type": "string",
                        "description": "Recurrence start date in format YYYY-MM-DD"
                      }
                    }
                  }
                ]
              },
              "examples": {
                "simple": {
                  "value": {
                    "amount": 10,
                    "currency": "484",
                    "reference": "123456789",
                    "customerInformation": {
                      "firstName": "Juan",
                      "lastName": "Lopez",
                      "middleName": "Perez",
                      "phone1": "5544332211",
                      "email": "juan@mail.com",
                      "city": "Ciudad de México",
                      "address1": "Av Constituyentes 908",
                      "postalCode": "11950",
                      "state": "Ciudad de México",
                      "country": "MX",
                      "ip": "0.0.0.0"
                    },
                    "cardData": {
                      "cardNumber": "4111111111111111",
                      "cvv": "123",
                      "cardholderName": "Juan Lopez Perez",
                      "expirationMonth": "12",
                      "expirationYear": "27"
                    }
                  }
                },
                "3DS": {
                  "value": {
                    "amount": 10,
                    "currency": "484",
                    "reference": "123456789",
                    "customerInformation": {
                      "firstName": "Juan",
                      "lastName": "Lopez",
                      "middleName": "Perez",
                      "phone1": "5544332211",
                      "email": "juan@mail.com",
                      "city": "Ciudad de México",
                      "address1": "Av Constituyentes 908",
                      "postalCode": "11950",
                      "state": "Ciudad de México",
                      "country": "MX",
                      "ip": "0.0.0.0"
                    },
                    "cardData": {
                      "cardNumber": "4111111111111111",
                      "cvv": "123",
                      "cardholderName": "Juan Lopez Perez",
                      "expirationMonth": "12",
                      "expirationYear": "27"
                    },
                    "redirectUrl": "https://link.etomin.com/confirmation"
                  }
                },
                "tokenCard": {
                  "value": {
                    "amount": 10,
                    "currency": "484",
                    "reference": "123456789",
                    "customerInformation": {
                      "firstName": "Juan",
                      "lastName": "Lopez",
                      "middleName": "Perez",
                      "phone1": "5544332211",
                      "email": "juan@mail.com",
                      "city": "Ciudad de México",
                      "address1": "Av Constituyentes 908",
                      "postalCode": "11950",
                      "state": "Ciudad de México",
                      "country": "MX",
                      "ip": "0.0.0.0"
                    },
                    "cardData": {
                      "cardNumberToken": "xxxxxxxxxxxxxxxxx",
                      "cvv": "123"
                    }
                  }
                },
                "recurrence": {
                  "value": {
                    "amount": 10,
                    "currency": "484",
                    "reference": "123456789",
                    "customerInformation": {
                      "firstName": "Juan",
                      "lastName": "Lopez",
                      "middleName": "Perez",
                      "phone1": "5544332211",
                      "email": "juan@mail.com",
                      "city": "Ciudad de México",
                      "address1": "Av Constituyentes 908",
                      "postalCode": "11950",
                      "state": "Ciudad de México",
                      "country": "MX",
                      "ip": "0.0.0.0"
                    },
                    "cardData": {
                      "cardNumberToken": "xxxxxxxxxxxxxxxxx",
                      "cvv": "123"
                    },
                    "planName": "Premium",
                    "recurrence": "monthly",
                    "startDate": "2024-09-01"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Operation success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "string",
                      "description": "Order Id"
                    },
                    "reference": {
                      "type": "string",
                      "description": "Description reference"
                    },
                    "amount": {
                      "type": "number",
                      "description": "Charge amount"
                    },
                    "customerEmail": {
                      "type": "string",
                      "description": "Client email"
                    },
                    "cardNumber": {
                      "type": "string",
                      "description": "Card number"
                    },
                    "authorizationNumber": {
                      "type": "string",
                      "description": "Authorization code transaction"
                    },
                    "transactionId": {
                      "type": "string",
                      "description": "Transaction request id"
                    },
                    "responseCode": {
                      "type": "string",
                      "description": "Response operation code"
                    },
                    "status": {
                      "type": "string",
                      "description": "Status transaction"
                    },
                    "mode": {
                      "type": "string",
                      "description": "Environment code"
                    },
                    "consolidate": {
                      "type": "string"
                    },
                    "statementAccount": {
                      "type": "string"
                    },
                    "orderId": {
                      "type": "string",
                      "description": "Order transaction Id"
                    }
                  }
                }
              }
            }
          },
          "403": {
            "description": "Not authorized"
          },
          "500": {
            "description": "Internal server error"
          }
        },
        "security": [
          {
            "BearerAuth": []
          }
        ]
      }
    },
    "/card/tokenizer": {
      "post": {
        "summary": "Card token",
        "tags": [
          "Sale"
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "cardData": {
                    "type": "object",
                    "properties": {
                      "cardNumber": {
                        "type": "string",
                        "description": "Credit card number"
                      },
                      "cardholderName": {
                        "type": "string",
                        "description": "Name on the credit card"
                      },
                      "expirationYear": {
                        "type": "string",
                        "description": "Card expiration year"
                      },
                      "expirationMonth": {
                        "type": "string",
                        "description": "Card expiration month"
                      }
                    }
                  }
                }
              },
              "example": {
                "cardData": {
                  "cardNumber": "4111111111111111",
                  "cardholderName": "Juan Lopez Perez",
                  "expirationMonth": "12",
                  "expirationYear": "27"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Card token generated successfully",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "cardNumber": {
                      "type": "string",
                      "description": "Card number"
                    },
                    "cardNumberToken": {
                      "type": "string",
                      "description": "Tokenized card number"
                    }
                  }
                }
              }
            }
          },
          "403": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "security": [
          {
            "BearerAuth": []
          }
        ]
      }
    },
    "/transaction/{orderId}": {
      "get": {
        "summary": "Payment information",
        "tags": [
          "Sale"
        ],
        "parameters": [
          {
            "in": "path",
            "name": "orderId",
            "schema": {
              "type": "string",
              "description": "Order transaction Id"
            },
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Successfully retrieved payment information",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "id": {
                        "type": "string",
                        "description": "Id of transaction"
                      },
                      "type": {
                        "type": "string",
                        "description": "Type transaction"
                      },
                      "cardNumber": {
                        "type": "string",
                        "description": "Card number"
                      },
                      "origin": {
                        "type": "string",
                        "description": "Payment origin"
                      },
                      "order": {
                        "type": "string",
                        "description": "Order Id"
                      },
                      "externalReference": {
                        "type": "string",
                        "description": "Reference"
                      },
                      "date": {
                        "type": "number",
                        "description": "Date of transaction"
                      },
                      "status": {
                        "type": "string",
                        "description": "Status transaction"
                      },
                      "authorizationCode": {
                        "type": "string",
                        "description": "Authorization code"
                      },
                      "amount": {
                        "type": "number",
                        "description": "Payment amount"
                      },
                      "referenceNumber": {
                        "type": "string",
                        "description": "Reference number"
                      },
                      "responseCode": {
                        "type": "string",
                        "description": "Code reponse"
                      },
                      "payer": {
                        "type": "object",
                        "description": "Payer info",
                        "properties": {
                          "mail": {
                            "type": "string",
                            "description": "Client email"
                          },
                          "fullName": {
                            "type": "string",
                            "description": "Client name"
                          }
                        }
                      },
                      "rateFee": {
                        "type": "string",
                        "description": "Rate fee"
                      },
                      "transactionFee": {
                        "type": "string",
                        "description": "Transaction Fee"
                      },
                      "feeTransactionAmount": {
                        "type": "string",
                        "description": "Fee transaction amount"
                      }
                    }
                  }
                }
              }
            }
          },
          "403": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "security": [
          {
            "BearerAuth": []
          }
        ]
      }
    },
    "/transaction/reference/{reference}": {
      "get": {
        "summary": "Payment information by reference",
        "tags": [
          "Sale"
        ],
        "parameters": [
          {
            "in": "path",
            "name": "reference",
            "schema": {
              "type": "string",
              "description": "Reference transaction"
            },
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Successfully retrieved payment information by reference",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "number",
                      "description": "Payment identifier"
                    },
                    "reference": {
                      "type": "string",
                      "description": "Id of transaction"
                    },
                    "amount": {
                      "type": "number",
                      "description": "Payment amount"
                    },
                    "customerEmail": {
                      "type": "string",
                      "description": "email of client"
                    },
                    "cardNumber": {
                      "type": "string",
                      "description": "Card number"
                    },
                    "authorizationNumber": {
                      "type": "string",
                      "description": "Authorization number"
                    },
                    "transactionId": {
                      "type": "string",
                      "description": "Id of transaction with the gateway"
                    },
                    "responseCode": {
                      "type": "string",
                      "description": "Code of response"
                    },
                    "responseMessage": {
                      "type": "string",
                      "description": "Message of response"
                    },
                    "status": {
                      "type": "string",
                      "description": "Status of transaction"
                    },
                    "mode": {
                      "type": "string",
                      "description": "Mode of transaction"
                    },
                    "orderId": {
                      "type": "string",
                      "description": "Order Id associated with the transaction"
                    }
                  }
                }
              }
            }
          },
          "403": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "security": [
          {
            "BearerAuth": []
          }
        ]
      }
    },
    "/refund": {
      "post": {
        "summary": "Refund sale",
        "tags": [
          "Sale"
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "orderId": {
                    "type": "string",
                    "description": "ID of the order to be refunded"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Operation success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "string",
                      "description": "Order Id"
                    },
                    "reference": {
                      "type": "string",
                      "description": "Description reference"
                    },
                    "amount": {
                      "type": "number",
                      "description": "Charge amount"
                    },
                    "customerEmail": {
                      "type": "string",
                      "description": "Client email"
                    },
                    "cardNumber": {
                      "type": "string",
                      "description": "Card number"
                    },
                    "authorizationNumber": {
                      "type": "string",
                      "description": "Authorization code transaction"
                    },
                    "transactionId": {
                      "type": "string",
                      "description": "Transaction request id"
                    },
                    "responseCode": {
                      "type": "string",
                      "description": "Response operation code"
                    },
                    "status": {
                      "type": "string",
                      "description": "Status transaction"
                    },
                    "mode": {
                      "type": "string",
                      "description": "Environment code"
                    },
                    "consolidate": {
                      "type": "string"
                    },
                    "statementAccount": {
                      "type": "string"
                    },
                    "orderId": {
                      "type": "string",
                      "description": "Order transaction Id"
                    }
                  }
                }
              }
            }
          },
          "403": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal server error"
          }
        },
        "security": [
          {
            "BearerAuth": []
          }
        ]
      }
    },
    "/reversal": {
      "post": {
        "summary": "Reversal sale",
        "tags": [
          "Sale"
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "orderId": {
                    "type": "string",
                    "description": "Order transaction Id"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Operation success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "string",
                      "description": "Order Id"
                    },
                    "reference": {
                      "type": "string",
                      "description": "Description reference"
                    },
                    "amount": {
                      "type": "number",
                      "description": "Charge amount"
                    },
                    "customerEmail": {
                      "type": "string",
                      "description": "Client email"
                    },
                    "cardNumber": {
                      "type": "string",
                      "description": "Card number"
                    },
                    "authorizationNumber": {
                      "type": "string",
                      "description": "Authorization code transaction"
                    },
                    "transactionId": {
                      "type": "string",
                      "description": "Transaction request id"
                    },
                    "responseCode": {
                      "type": "string",
                      "description": "Response operation code"
                    },
                    "status": {
                      "type": "string",
                      "description": "Status transaction"
                    },
                    "mode": {
                      "type": "string",
                      "description": "Environment code"
                    },
                    "consolidate": {
                      "type": "string"
                    },
                    "statementAccount": {
                      "type": "string"
                    },
                    "orderId": {
                      "type": "string",
                      "description": "Order transaction Id"
                    }
                  }
                }
              }
            }
          },
          "403": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal server error"
          }
        },
        "security": [
          {
            "BearerAuth": []
          }
        ]
      }
    },
    "/cards": {
      "get": {
        "summary": "Get tokenized cards",
        "tags": [
          "Get Cards"
        ],
        "responses": {
          "200": {
            "description": "Successfully retrieved tokenized cards",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "cardNumber": {
                        "type": "string",
                        "description": "Mask of card"
                      },
                      "cardNumberToken": {
                        "type": "string",
                        "description": "Card token"
                      }
                    }
                  }
                }
              }
            }
          },
          "403": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "security": [
          {
            "BearerAuth": []
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "BearerAuth": {
        "type": "http",
        "scheme": "bearer"
      }
    },
    "schemas": {
      "simple": {
        "properties": {
          "amount": {
            "type": "number",
            "description": "Sale amount"
          },
          "currency": {
            "type": "string",
            "description": "Currency code"
          },
          "reference": {
            "type": "string",
            "description": "Transaction reference"
          },
          "customerInformation": {
            "type": "object",
            "properties": {
              "firstName": {
                "type": "string",
                "description": "Customer's first name"
              },
              "lastName": {
                "type": "string",
                "description": "Customer's last name"
              },
              "middleName": {
                "type": "string",
                "description": "Customer's middle name"
              },
              "email": {
                "type": "string",
                "description": "Customer's email address"
              },
              "phone1": {
                "type": "string",
                "description": "Customer's phone number"
              },
              "city": {
                "type": "string",
                "description": "Customer's city"
              },
              "address1": {
                "type": "string",
                "description": "Customer's address"
              },
              "postalCode": {
                "type": "string",
                "description": "Customer's postal code"
              },
              "state": {
                "type": "string",
                "description": "Customer's state"
              },
              "country": {
                "type": "string",
                "description": "Customer's country"
              },
              "ip": {
                "type": "string",
                "description": "Customer's IP address"
              }
            }
          },
          "cardData": {
            "type": "object",
            "properties": {
              "cardNumber": {
                "type": "string",
                "description": "Credit card number"
              },
              "cvv": {
                "type": "string",
                "description": "Credit card security code (CVV)"
              },
              "cardholderName": {
                "type": "string",
                "description": "Name of the cardholder"
              },
              "expirationYear": {
                "type": "string",
                "description": "Card expiration year"
              },
              "expirationMonth": {
                "type": "string",
                "description": "Card expiration month"
              }
            }
          }
        }
      },
      "3DS": {
        "properties": {
          "amount": {
            "type": "number",
            "description": "Sale amount"
          },
          "currency": {
            "type": "string",
            "description": "Currency code"
          },
          "reference": {
            "type": "string",
            "description": "Transaction reference"
          },
          "customerInformation": {
            "type": "object",
            "properties": {
              "firstName": {
                "type": "string",
                "description": "Customer's first name"
              },
              "lastName": {
                "type": "string",
                "description": "Customer's last name"
              },
              "middleName": {
                "type": "string",
                "description": "Customer's middle name"
              },
              "email": {
                "type": "string",
                "description": "Customer's email address"
              },
              "phone1": {
                "type": "string",
                "description": "Customer's phone number"
              },
              "city": {
                "type": "string",
                "description": "Customer's city"
              },
              "address1": {
                "type": "string",
                "description": "Customer's address"
              },
              "postalCode": {
                "type": "string",
                "description": "Customer's postal code"
              },
              "state": {
                "type": "string",
                "description": "Customer's state"
              },
              "country": {
                "type": "string",
                "description": "Customer's country"
              },
              "ip": {
                "type": "string",
                "description": "Customer's IP address"
              }
            }
          },
          "cardData": {
            "type": "object",
            "properties": {
              "cardNumber": {
                "type": "string",
                "description": "Credit card number"
              },
              "cvv": {
                "type": "string",
                "description": "Credit card security code (CVV)"
              },
              "cardholderName": {
                "type": "string",
                "description": "Name of the cardholder"
              },
              "expirationYear": {
                "type": "string",
                "description": "Card expiration year"
              },
              "expirationMonth": {
                "type": "string",
                "description": "Card expiration month"
              }
            }
          },
          "redirectUrl": {
            "type": "string",
            "description": "Redirect URL with response"
          }
        }
      },
      "tokenCard": {
        "properties": {
          "amount": {
            "type": "number",
            "description": "Sale amount"
          },
          "currency": {
            "type": "string",
            "description": "Currency code"
          },
          "reference": {
            "type": "string",
            "description": "Transaction reference"
          },
          "customerInformation": {
            "type": "object",
            "properties": {
              "firstName": {
                "type": "string",
                "description": "Customer's first name"
              },
              "lastName": {
                "type": "string",
                "description": "Customer's last name"
              },
              "middleName": {
                "type": "string",
                "description": "Customer's middle name"
              },
              "email": {
                "type": "string",
                "description": "Customer's email address"
              },
              "phone1": {
                "type": "string",
                "description": "Customer's phone number"
              },
              "city": {
                "type": "string",
                "description": "Customer's city"
              },
              "address1": {
                "type": "string",
                "description": "Customer's address"
              },
              "postalCode": {
                "type": "string",
                "description": "Customer's postal code"
              },
              "state": {
                "type": "string",
                "description": "Customer's state"
              },
              "country": {
                "type": "string",
                "description": "Customer's country"
              },
              "ip": {
                "type": "string",
                "description": "Customer's IP address"
              }
            }
          },
          "cardData": {
            "type": "object",
            "properties": {
              "cardNumberToken": {
                "type": "string",
                "description": "Card token"
              },
              "cvv": {
                "type": "string",
                "description": "Credit card security code (CVV)"
              }
            }
          }
        }
      },
      "recurrence": {
        "properties": {
          "amount": {
            "type": "number",
            "description": "Sale amount"
          },
          "currency": {
            "type": "string",
            "description": "Currency code"
          },
          "reference": {
            "type": "string",
            "description": "Transaction reference"
          },
          "customerInformation": {
            "type": "object",
            "properties": {
              "firstName": {
                "type": "string",
                "description": "Customer's first name"
              },
              "lastName": {
                "type": "string",
                "description": "Customer's last name"
              },
              "middleName": {
                "type": "string",
                "description": "Customer's middle name"
              },
              "email": {
                "type": "string",
                "description": "Customer's email address"
              },
              "phone1": {
                "type": "string",
                "description": "Customer's phone number"
              },
              "city": {
                "type": "string",
                "description": "Customer's city"
              },
              "address1": {
                "type": "string",
                "description": "Customer's address"
              },
              "postalCode": {
                "type": "string",
                "description": "Customer's postal code"
              },
              "state": {
                "type": "string",
                "description": "Customer's state"
              },
              "country": {
                "type": "string",
                "description": "Customer's country"
              },
              "ip": {
                "type": "string",
                "description": "Customer's IP address"
              }
            }
          },
          "cardData": {
            "type": "object",
            "properties": {
              "cardNumberToken": {
                "type": "string",
                "description": "Card token"
              },
              "cvv": {
                "type": "string",
                "description": "Credit card security code (CVV)"
              }
            }
          },
          "planName": {
            "type": "string",
            "description": "Recurrence plan name"
          },
          "recurrence": {
            "type": "string",
            "description": "Recurrence value"
          },
          "startDate": {
            "type": "string",
            "description": "Recurrence start date in format YYYY-MM-DD"
          }
        }
      }
    }
  },
  "x-readme": {
    "explorer-enabled": true,
    "proxy-enabled": true
  }
}